import {
  Battery,
  BottleWine,
  Boxes,
  CupSoda,
  FileText,
  Flame,
  Hammer,
  Lightbulb,
  type LucideIcon,
  Plug,
  Recycle,
  Shirt,
  SprayCan,
  Wrench,
  XCircle,
} from "lucide-react";

export const wasteTypeIcons: Record<string, LucideIcon> = {
  ペットボトル: Recycle,
  可燃ごみ: Flame,
  収集不可: XCircle,
  収集不可2: XCircle,
  破砕ごみ: Hammer,
  粗大ごみ: Boxes,
  "資源(びん)": BottleWine,
  "資源(スプレー缶)": SprayCan,
  "資源(ライター)": Flame,
  "資源(乾電池)": Battery,
  "資源(小型家電)": Plug,
  "資源(布・衣類)": Shirt,
  "資源(紙類)": FileText,
  "資源(蛍光管)": Lightbulb,
  "資源(金属類)": Wrench,
  "資源(飲料缶)": CupSoda,
};
